run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number

linters:
  disable-all: true
  enable:
    # correctness / bugs
    - govet
    - errcheck
    - staticcheck
    - typecheck
    - ineffassign
    - unused

    # code quality / cleanup (generally low-noise)
    - unconvert
    - unparam

    # formatting / imports
    - gofmt
    - goimports

    # style (kept minimal; tune as needed)
    - revive

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: stego
  revive:
    ignore-generated-header: true
    rules:
      - name: blank-imports
      - name: context-keys-type
      - name: empty-block
      - name: error-strings
      - name: error-naming
      - name: exported
        arguments:
          - disableStutteringCheck
      - name: if-return
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: redundant-import-alias
      - name: time-naming
      - name: var-declaration

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-dirs:
    - frontend
    - build
    - images
    - data
    - python_example
    - error
