// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {log} from '../models';

export function CancelDecrypt(arg1:string):Promise<void>;

export function CancelEncrypt(arg1:string):Promise<void>;

export function CancelGenerate(arg1:string):Promise<void>;

export function ClearLogs():Promise<void>;

export function ExportLogs(arg1:string,arg2:number,arg3:number):Promise<string>;

export function ExportLogsToFile(arg1:string,arg2:number,arg3:number):Promise<string>;

export function GetAppInfo():Promise<models.AppInfo>;

export function GetConfig():Promise<Record<string, string>>;

export function GetLogs(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<Array<log.Entry>>;

export function GetLogsCount():Promise<number>;

export function LogUserAction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function SaveConfig(arg1:Record<string, string>):Promise<void>;

export function StartDecrypt(arg1:models.DecryptRequest):Promise<string>;

export function StartEncrypt(arg1:models.EncryptRequest):Promise<string>;

export function StartGenerateCarrier(arg1:models.GenerateRequest):Promise<string>;
