// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDecrypt(arg1) {
  return window['go']['main']['App']['CancelDecrypt'](arg1);
}

export function CancelEncrypt(arg1) {
  return window['go']['main']['App']['CancelEncrypt'](arg1);
}

export function CancelGenerate(arg1) {
  return window['go']['main']['App']['CancelGenerate'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ExportLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportLogs'](arg1, arg2, arg3);
}

export function ExportLogsToFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportLogsToFile'](arg1, arg2, arg3);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2, arg3, arg4, arg5);
}

export function GetLogsCount() {
  return window['go']['main']['App']['GetLogsCount']();
}

export function LogUserAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogUserAction'](arg1, arg2, arg3);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartDecrypt(arg1) {
  return window['go']['main']['App']['StartDecrypt'](arg1);
}

export function StartEncrypt(arg1) {
  return window['go']['main']['App']['StartEncrypt'](arg1);
}

export function StartGenerateCarrier(arg1) {
  return window['go']['main']['App']['StartGenerateCarrier'](arg1);
}
